name: "Bug report"
description: "Template for bug reports"
labels: [ bug ]
body:
  - type: textarea
    attributes:
      label: "Issue description"
      description: "Please describe the issue you're experiencing as detailed as possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "To reproduce"
      description: "How can the bug be reproduced?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots / videos"
      description: "Link screenshots and videos here if you have any"
    validations:
      required: false
  - type: input
    attributes:
      label: "MCHR version"
      description: "MCHR version"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional information"
      description: "Anything else you want to share?"
    validations:
      required: false